name: Docker Deploy

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            khulnasoft/issue-manager:latest
            ghcr.io/khulnasoft/issue-manager:latest
          file: base.dockerfile
      - name: Build and push tag
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            khulnasoft/issue-manager:${{ github.event.release.tag_name }}
            ghcr.io/khulnasoft/issue-manager:${{ github.event.release.tag_name }}
          file: base.dockerfile
